name: Release

on:
  push:
    branches: [ main, dev ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test Build & Extension
        run: |
          chmod +x build.sh
          ./build.sh dev test-version
          
          # Verify build artifacts exist
          if [ -z "$(ls bamboo-plus-v*.zip 2>/dev/null)" ]; then
            echo "❌ Build failed: ZIP file not created"
            exit 1
          fi
          if [ ! -f "bamboo-plus.user.js" ]; then
            echo "❌ Build failed: Userscript not created"
            exit 1
          fi

          # Check required files exist
          required_files=("manifest.json" "background.js" "popup.html" "popup.js" "bamboo-plus.user.js")
          for file in "${required_files[@]}"; do
            if [ ! -f "extension/$file" ]; then
              echo "❌ Missing required file: $file"
              exit 1
            fi
          done
          
          # Validate manifest.json
          if ! jq empty extension/manifest.json; then
            echo "❌ Invalid manifest.json"
            exit 1
          fi
          
          # Validate userscript metadata
          if ! grep -q "@name" extension/bamboo-plus.user.js; then
            echo "❌ Missing @name in userscript"
            exit 1
          fi
          if ! grep -q "@version" extension/bamboo-plus.user.js; then
            echo "❌ Missing @version in userscript"
            exit 1
          fi

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release 