name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: |
          VERSION=$(grep '"version":' manifest.json | cut -d'"' -f4)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create release zip
        run: |
          cd extension
          zip -r ../bamboo-plus-v${{ steps.get_version.outputs.version }}.zip *

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Extension ZIP
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bamboo-plus-v${{ steps.get_version.outputs.version }}.zip
          asset_name: bamboo-plus-v${{ steps.get_version.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload Userscript
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bamboo-plus.user.js
          asset_name: bamboo-plus.user.js
          asset_content_type: text/javascript 