name: Test Build & Extension

on:
  workflow_call:

jobs:
  test:
    name: Test Build & Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Build
        run: |
          ./build.sh dev
          
          # Verify build artifacts
          if [ ! -f "bamboo-plus-"*".zip" ]; then
            echo "❌ Build failed: ZIP file not found"
            exit 1
          fi
          
          # Check extension structure
          if [ ! -f "build/manifest.json" ] || \
             [ ! -f "build/bamboo-plus.user.js" ] || \
             [ ! -f "build/background.js" ] || \
             [ ! -f "build/popup.html" ] || \
             [ ! -f "build/popup.js" ]; then
            echo "❌ Build failed: Missing required files"
            exit 1
          fi
          
          # Validate manifest.json
          if ! jq empty build/manifest.json 2>/dev/null; then
            echo "❌ Build failed: Invalid manifest.json"
            exit 1
          fi
          
          # Check userscript metadata
          if ! grep -q "@name.*BambooHR Plus" build/bamboo-plus.user.js || \
             ! grep -q "@version" build/bamboo-plus.user.js || \
             ! grep -q "@description" build/bamboo-plus.user.js; then
            echo "❌ Build failed: Invalid userscript metadata"
            exit 1
          fi
          
          echo "✅ Build and validation successful" 